import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Server,Monitor,ArrowRight,ArrowLeft,RefreshCw,ArrowUp,Folder,FileText}from'lucide-react';
import './style.css';
const defaults={host:'',port:'21',user:'anonymous',password:'',protocol:'FTP',encoding:'utf8',ignoreCertificate:true};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
const initial={...defaults,...read('ftpview.connection',{})};
async function api(url,body){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);let d;try{d=await r.json();}catch{throw new Error('无法访问后端，请确认已重启 npm run start');}if(!r.ok)throw new Error(d.error||'请求失败');return d;}
function Pane({title,remote,items,path,load,busy,enabled=true}){
 const [draft,setDraft]=useState(path),[selected,setSelected]=useState('');
 useEffect(()=>{setDraft(path);setSelected('');},[path]);
 return <section className="pane"><div className="pane-head"><div className="pane-title">{remote?<Server/>:<Monitor/>}<b>{title}</b></div><form className="path" onSubmit={e=>{e.preventDefault();load(draft);}}><input aria-label={title+'目录'} value={draft} onChange={e=>setDraft(e.target.value)} disabled={!enabled||busy}/><button disabled={!enabled||busy} title="打开目录"><ArrowRight size={16}/></button></form><div className="nav"><button disabled={!enabled||busy} onClick={()=>load(path.replace(/\/$/,'')+'/..')} title="上级目录"><ArrowUp/></button><button disabled={!enabled||busy} onClick={()=>load(path)} title="刷新"><RefreshCw/></button></div></div><div className="toolbar">{busy?'正在读取目录…':enabled?'双击文件夹打开 · 输入路径后按回车': '请先连接 FTP 服务器'}<span className="count">{items.length} 项</span></div><div className="table"><div className="tr th"><span>名称</span><span>大小</span><span>类型</span><span>修改时间</span></div>{enabled&&<button className="tr file-row" disabled={busy} onDoubleClick={()=>load(path.replace(/\/$/,'')+'/..')}><span><Folder className="ico folder"/>..</span></button>}{items.map(x=><button disabled={busy} className={'tr file-row '+(selected===x.name?'selected':'')} key={x.name} onClick={()=>setSelected(x.name)} onDoubleClick={()=>x.type==='folder'&&load(path.replace(/\/$/,'')+'/'+x.name)}><span title={x.name}>{x.type==='folder'?<Folder className="ico folder"/>:<FileText className="ico file"/>}{x.name}</span><span>{x.type==='folder'?'—':x.size>1048576?(x.size/1048576).toFixed(1)+' MB':(x.size/1024).toFixed(1)+' KB'}</span><span>{x.type==='folder'?'文件夹':'文件'}</span><span>{x.modifiedAt?new Date(x.modifiedAt).toLocaleString('zh-CN'): '—'}</span></button>)}</div></section>;
}
function App(){
 const [config,setConfig]=useState(initial),[active,setActive]=useState(null),[local,setLocal]=useState({path:'',files:[]}),[remote,setRemote]=useState({path:'/',files:[]}),[localBusy,setLocalBusy]=useState(false),[ftpBusy,setFtpBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
 function notice(text,failed=false){setMessage(text);setError(failed);}
 function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{notice('浏览器不允许保存设置，当前会话仍可使用',true);}}
 async function localLoad(p='',fallback=false){setLocalBusy(true);try{const d=await api('/api/local/list?path='+encodeURIComponent(p));setLocal(d);save('ftpview.localPath',d.path);}catch(e){if(fallback&&p){await localLoad('');notice('上次目录不可用，已尝试打开用户主目录',true);}else notice('本机目录：'+e.message,true);}finally{setLocalBusy(false);}}
 async function ftpLoad(p='/',settings=active){if(!settings)return;setFtpBusy(true);notice('正在连接并读取 FTP 目录…');try{const d=await api('/api/ftp/list',{...settings,remotePath:p});setRemote(d);setActive({...settings});save('ftpview.connection',settings);notice('FTP 目录已加载');}catch(e){notice('FTP：'+e.message,true);}finally{setFtpBusy(false);}}
 useEffect(()=>{localLoad(read('ftpview.localPath',''),true);},[]);
 function change(key,value){const next={...config,[key]:value};setConfig(next);save('ftpview.connection',next);}
 return <div className="app"><header><div className="traffic"><i/><i/><i/></div><Server/><span>FTPView · 网页版 FTP 工具</span></header><form className="connect" onSubmit={e=>{e.preventDefault();setActive(null);setRemote({path:'/',files:[]});ftpLoad('/',config);}}><label>主机:<input required value={config.host} disabled={ftpBusy} onChange={e=>change('host',e.target.value)} placeholder="FTP 服务器地址"/></label><label>端口:<input required type="number" min="1" max="65535" value={config.port} disabled={ftpBusy} onChange={e=>change('port',e.target.value)}/></label><label>用户名:<input value={config.user} disabled={ftpBusy} onChange={e=>change('user',e.target.value)}/></label><label>密码:<input type="password" value={config.password} disabled={ftpBusy} onChange={e=>change('password',e.target.value)}/></label><select aria-label="协议" disabled={ftpBusy} value={config.protocol} onChange={e=>change('protocol',e.target.value)}><option>FTP</option><option>FTPS</option><option value="FTPS implicit">FTPS 隐式</option></select><button disabled={ftpBusy} className="primary">{ftpBusy?'连接中…':active?'重新连接':'连接'}</button>{active&&<button type="button" disabled={ftpBusy} onClick={()=>{setActive(null);setRemote({path:'/',files:[]});notice('已断开');}}>断开</button>}</form><div className="options"><label>文件名编码 <select disabled={ftpBusy} value={config.encoding} onChange={e=>change('encoding',e.target.value)}>{[['utf8','UTF-8'],['gbk','GBK（简体中文）'],['gb18030','GB18030'],['big5','Big5（繁体中文）'],['latin1','Latin-1']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label><input type="checkbox" disabled={ftpBusy||config.protocol==='FTP'} checked={config.ignoreCertificate} onChange={e=>change('ignoreCertificate',e.target.checked)}/>忽略 FTPS 证书校验</label><span>连接信息（含密码）仅保存在此浏览器 · 修改配置后点击连接生效</span><button onClick={()=>{localStorage.removeItem('ftpview.connection');setConfig({...defaults});notice('已清除保存的连接信息');}} disabled={ftpBusy}>忘记连接信息</button></div>{message&&<div role="status" className={'notice '+(error?'error':'')}>{message}</div>}<main><div className="panes"><Pane title="本机文件" items={local.files} path={local.path} load={localLoad} busy={localBusy}/><div className="middle"><button title="刷新两侧目录" onClick={()=>{localLoad(local.path);if(active)ftpLoad(remote.path);}} disabled={localBusy||ftpBusy}><RefreshCw/>刷新</button></div><Pane title="FTP 服务器" remote items={remote.files} path={remote.path} load={ftpLoad} busy={ftpBusy} enabled={!!active}/></div></main><footer><span className={active?'green':'gray'}>●</span>{active?'已连接到 '+active.host+':'+active.port:'FTP 未连接'}<span className="status">本机目录自动记忆</span></footer></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
